### ISSUE TITLE
Documentation for users unfamiliar with rust

### ISSUE THREAD

**Issue by madonius** [Acizza/nixos-update-status#1]
The nature of the code does not suggest the user is familiar with rust and it's build environment.
It would be good to have a "execute those commands and your $bar will display the number of pending packages" section.

**Comment by jonathanlmc** [comment]
Hello.

I've updated the README to explain everything in more detail. Please let me know if it's helpful enough.

**Comment by madonius** [comment]
Thank you very much :)
